# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VaccinationCenter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift', '6.2.0'
pod 'RxCocoa', '6.2.0'
pod 'SnapKit', '~> 5.0.0'
pod 'Alamofire', '~> 5.4'

  # Pods for VaccinationCenter

  target 'VaccinationCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VaccinationCenterUITests' do
    # Pods for testing
  end

end
